"""Añadir ajustes plantillas

Revision ID: 0c0b105ff946
Revises: 115d679bd24b
Create Date: 2025-04-22 15:08:17.044717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0b105ff946'
down_revision = '115d679bd24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aprobado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('aprobado')

    # ### end Alembic commands ###
