"""Agregar columna

Revision ID: 0c3381ab8b08
Revises: ab7088e7e48b
Create Date: 2025-04-23 14:57:40.719264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c3381ab8b08'
down_revision = 'ab7088e7e48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_cambios', schema=None) as batch_op:
        batch_op.alter_column('item_registro',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_cambios', schema=None) as batch_op:
        batch_op.alter_column('item_registro',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
