"""Añadir campos rol y ultimo_acceso a usuario

Revision ID: 115d679bd24b
Revises: a0ebd304aafb
Create Date: 2025-04-22 10:07:46.476696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '115d679bd24b'
down_revision = 'a0ebd304aafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_acceso', sa.DateTime(), nullable=True))
        batch_op.alter_column('rol',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('ultimo_acceso')

    # ### end Alembic commands ###
