"""arreglar historial

Revision ID: 4de3f37926c6
Revises: 0c3381ab8b08
Create Date: 2025-04-23 15:02:11.883762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de3f37926c6'
down_revision = '0c3381ab8b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_cambios', schema=None) as batch_op:
        batch_op.drop_constraint('log_cambios_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_cambios', schema=None) as batch_op:
        batch_op.create_foreign_key('log_cambios_ibfk_2', 'producto', ['product_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
