"""Agregar columna tabla_afectada a Logcambio

Revision ID: ab7088e7e48b
Revises: 0c0b105ff946
Create Date: 2025-04-23 13:10:09.703546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7088e7e48b'
down_revision = '0c0b105ff946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_cambios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tabla_afectada', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_cambios', schema=None) as batch_op:
        batch_op.drop_column('tabla_afectada')

    # ### end Alembic commands ###
